version: '3'
services:
  app:
    container_name: docker-express-mongo
    restart: always
    build: .
    ports:
      - '3001:3001'
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'